# Generated by Django 5.1.3 on 2024-11-26 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Economation', '0002_user_delete_fisiculturistas'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagensSuporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mensagem', models.CharField(max_length=500)),
            ],
        ),
    ]
