# Generated by Django 5.1.3 on 2024-11-26 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Economation', '0004_rename_tel_mensagenssuporte_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=50)),
                ('data', models.DateField(auto_now_add=True, verbose_name='Criado em')),
            ],
        ),
    ]
