# Generated by Django 5.1.3 on 2024-11-28 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Economation', '0005_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagenssuporte',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='mensagenssuporte',
            name='mensagem',
            field=models.TextField(),
        ),
    ]
